#include "UserCodeHarness.h"
#include <fstream>
#include <sstream>
#include <random>
#include <chrono>
#include <algorithm>
#include <cmath>
#include <cctype>
#include <cstring>
#include <set>

#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <windows.h>

UserCodeHarness::UserCodeHarness() = default;

UserCodeHarness::~UserCodeHarness() {
    Unload();
}

std::string UserCodeHarness::DefaultUserMainTemplate() {
    return
        "// 写完整生命周期即可。压测 / 多线程 / 多型号并发都会直接调用本函数。\n"
        "// 多型号：每种弹各自编译一份 UserMain（头文件/DLL 可不同），再按数量并行一起跑。\n"
        "// 授权文件请与 models/ 下的第三方 .dll 同级放置。\n"
        "// 模型包目录结构：根目录/include（头文件）、根目录/lib（.lib）、根目录/models（.dll）。\n"
        "// 每步用 out_lat / out_lon 接收经纬度，并 RecordTrajectoryPoint 供二维轨迹预览。\n"
        "// 样例模型包：dist/sample_models/PrecheckDemoWeapon（Model_Create/Init/Step/Destroy）\n"
        "\n"
        "void* handle = Model_Create();\n"
        "if (!handle) return -1;\n"
        "\n"
        "WeaponModelParams p{};\n"
        "p.init_lat = R.lat;\n"
        "p.init_lon = R.lon;\n"
        "p.init_alt = R.alt;\n"
        "p.init_speed = R.speed;\n"
        "p.init_heading = 45.0;\n"
        "p.init_pitch = 15.0;\n"
        "p.init_roll = 0.0;\n"
        "p.step_dt = 0.02;\n"
        "\n"
        "if (Model_Init(handle, &p) != 0) { Model_Destroy(handle); return -1; }\n"
        "for (int i = 0; i < 100; ++i) {\n"
        "    WeaponModelOutput o{};\n"
        "    if (Model_Step(handle, &o) != 0) { Model_Destroy(handle); return -2; }\n"
        "    double out_lat = o.lat;\n"
        "    double out_lon = o.lon;\n"
        "    RecordTrajectoryPoint(out_lat, out_lon);\n"
        "}\n"
        "Model_Destroy(handle);\n"
        "return 0;\n";
}

std::string UserCodeHarness::FindVcVars64Bat() {
    wchar_t* pf86 = nullptr;
    size_t len = 0;
    _wdupenv_s(&pf86, &len, L"ProgramFiles(x86)");
    std::wstring base = pf86 ? pf86 : L"C:\\Program Files (x86)";
    if (pf86) free(pf86);

    std::wstring vswhere = base + L"\\Microsoft Visual Studio\\Installer\\vswhere.exe";
    if (GetFileAttributesW(vswhere.c_str()) == INVALID_FILE_ATTRIBUTES) {
        // fallback common paths
        const wchar_t* candidates[] = {
            L"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat",
            L"C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Auxiliary\\Build\\vcvars64.bat",
            L"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat"
        };
        for (const wchar_t* c : candidates) {
            if (GetFileAttributesW(c) != INVALID_FILE_ATTRIBUTES) {
                int n = WideCharToMultiByte(CP_UTF8, 0, c, -1, nullptr, 0, nullptr, nullptr);
                std::string s(n > 0 ? n - 1 : 0, '\0');
                if (n > 1) WideCharToMultiByte(CP_UTF8, 0, c, -1, &s[0], n, nullptr, nullptr);
                return s;
            }
        }
        return {};
    }

    // vswhere -latest -property installationPath
    SECURITY_ATTRIBUTES sa{};
    sa.nLength = sizeof(sa);
    sa.bInheritHandle = TRUE;
    HANDLE hRead = NULL, hWrite = NULL;
    CreatePipe(&hRead, &hWrite, &sa, 0);
    SetHandleInformation(hRead, HANDLE_FLAG_INHERIT, 0);

    std::wstring cmd = L"\"" + vswhere + L"\" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath";
    STARTUPINFOW si{};
    si.cb = sizeof(si);
    si.dwFlags = STARTF_USESTDHANDLES;
    si.hStdOutput = hWrite;
    si.hStdError = hWrite;
    PROCESS_INFORMATION pi{};
    std::wstring mutableCmd = cmd;
    if (!CreateProcessW(nullptr, &mutableCmd[0], nullptr, nullptr, TRUE, CREATE_NO_WINDOW, nullptr, nullptr, &si, &pi)) {
        CloseHandle(hRead); CloseHandle(hWrite);
        return {};
    }
    CloseHandle(hWrite);
    std::string out;
    char buf[512];
    DWORD rd = 0;
    while (ReadFile(hRead, buf, sizeof(buf), &rd, nullptr) && rd > 0) {
        out.append(buf, buf + rd);
    }
    WaitForSingleObject(pi.hProcess, 15000);
    CloseHandle(pi.hProcess); CloseHandle(pi.hThread); CloseHandle(hRead);

    // trim
    while (!out.empty() && (out.back() == '\n' || out.back() == '\r' || out.back() == ' ')) out.pop_back();
    size_t b = 0;
    while (b < out.size() && (out[b] == ' ' || out[b] == '\n' || out[b] == '\r')) ++b;
    out = out.substr(b);
    if (out.empty()) return {};
    return out + "\\VC\\Auxiliary\\Build\\vcvars64.bat";
}

std::string UserCodeHarness::GenerateSource(const UserHarnessConfig& config, const std::vector<RandomVarDef>& enabled) const {
    std::ostringstream ss;
    ss << "// Auto-generated by ModelPrecheck UserCodeHarness — do not edit permanently\n";
    ss << "#define NOMINMAX\n";
    ss << "#include <windows.h>\n";
    ss << "#include <cstdint>\n";
    ss << "#include <cstring>\n";
    ss << "#include <cmath>\n";
    ss << "#include <string>\n";
    ss << "#include <vector>\n\n";

    for (const auto& h : config.headerPaths) {
        // Use forward slashes in include string
        std::string p = h;
        for (char& c : p) if (c == '\\') c = '/';
        ss << "#include \"" << p << "\"\n";
    }
    ss << "\n";

    ss << "struct RandomBag {\n";
    for (const auto& v : enabled) {
        if (v.type == RandomVarType::Int)
            ss << "    int " << v.name << ";\n";
        else
            ss << "    double " << v.name << ";\n";
    }
    if (enabled.empty()) {
        ss << "    int _placeholder;\n";
    }
    ss << "};\n\n";

    // Trajectory buffer available to UserMain via RecordTrajectoryPoint(out_lat, out_lon)
    ss << "static std::vector<double> g_trajLat;\n";
    ss << "static std::vector<double> g_trajLon;\n";
    ss << "static int g_trajCapture = 0;\n\n";
    ss << "static void RecordTrajectoryPoint(double lat, double lon) {\n";
    ss << "    if (!g_trajCapture) return;\n";
    ss << "    g_trajLat.push_back(lat);\n";
    ss << "    g_trajLon.push_back(lon);\n";
    ss << "}\n\n";
    ss << "extern \"C\" __declspec(dllexport) void SetTrajectoryCapture(int on) {\n";
    ss << "    g_trajCapture = on ? 1 : 0;\n";
    ss << "    if (on) { g_trajLat.clear(); g_trajLon.clear(); }\n";
    ss << "}\n\n";
    ss << "extern \"C\" __declspec(dllexport) int GetTrajectoryCount() {\n";
    ss << "    return static_cast<int>(g_trajLat.size());\n";
    ss << "}\n\n";
    ss << "extern \"C\" __declspec(dllexport) int GetTrajectoryPoint(int i, double* lat, double* lon) {\n";
    ss << "    if (i < 0 || i >= static_cast<int>(g_trajLat.size())) return 0;\n";
    ss << "    if (lat) *lat = g_trajLat[static_cast<size_t>(i)];\n";
    ss << "    if (lon) *lon = g_trajLon[static_cast<size_t>(i)];\n";
    ss << "    return 1;\n";
    ss << "}\n\n";

    ss << "static int UserMain(const RandomBag& R) {\n";
    ss << config.userMainBody << "\n";
    ss << "}\n\n";

    ss << "extern \"C\" __declspec(dllexport) int RunUserTest(\n";
    ss << "    const double* dvals, int nd,\n";
    ss << "    const int* ivals, int ni)\n";
    ss << "{\n";
    ss << "    RandomBag R{};\n";
    int di = 0, ii = 0;
    for (const auto& v : enabled) {
        if (v.type == RandomVarType::Int) {
            ss << "    if (" << ii << " < ni) R." << v.name << " = ivals[" << ii << "];\n";
            ++ii;
        } else {
            ss << "    if (" << di << " < nd) R." << v.name << " = dvals[" << di << "];\n";
            ++di;
        }
    }
    ss << "    return UserMain(R);\n";
    ss << "}\n";
    return ss.str();
}

static std::wstring Utf8ToWide(const std::string& utf8) {
    if (utf8.empty()) return std::wstring();
    int n = MultiByteToWideChar(CP_UTF8, 0, utf8.c_str(), -1, nullptr, 0);
    if (n <= 1) return std::wstring();
    std::wstring w(static_cast<size_t>(n - 1), L'\0');
    MultiByteToWideChar(CP_UTF8, 0, utf8.c_str(), -1, &w[0], n);
    return w;
}

/** Copy *.dll under searchDirs into destDir so LoadLibrary(ALTERED_PATH) finds deps.
 *  Never overwrite harnessDllPath (same basename as model DLL is a common collision). */
static void CopyDependencyDllsBesideHarness(const std::vector<std::string>& searchDirs,
                                            const std::string& destDir,
                                            const std::string& harnessDllPath,
                                            std::string& log) {
    if (destDir.empty()) return;
    std::string harnessName;
    {
        const size_t slash = harnessDllPath.find_last_of("/\\");
        harnessName = (slash == std::string::npos)
            ? harnessDllPath : harnessDllPath.substr(slash + 1);
    }
    std::set<std::string> copiedNames;
    for (const auto& root : searchDirs) {
        if (root.empty()) continue;
        std::vector<std::string> stack;
        stack.push_back(root);
        int visited = 0;
        while (!stack.empty() && visited < 64) {
            const std::string dir = stack.back();
            stack.pop_back();
            ++visited;
            WIN32_FIND_DATAA data{};
            const std::string pattern = dir + "\\*";
            HANDLE find = FindFirstFileA(pattern.c_str(), &data);
            if (find == INVALID_HANDLE_VALUE) continue;
            do {
                if (strcmp(data.cFileName, ".") == 0 || strcmp(data.cFileName, "..") == 0)
                    continue;
                const std::string full = dir + "\\" + data.cFileName;
                if (data.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) {
                    if (visited < 64) stack.push_back(full);
                    continue;
                }
                const char* ext = strrchr(data.cFileName, '.');
                if (!ext || _stricmp(ext, ".dll") != 0) continue;
                if (!harnessName.empty() && _stricmp(data.cFileName, harnessName.c_str()) == 0) {
                    log += "INFO: 跳过与 Harness 同名的模型 DLL（避免覆盖）: ";
                    log += data.cFileName;
                    log += "\n";
                    continue;
                }
                if (!copiedNames.insert(data.cFileName).second) continue;
                const std::string dest = destDir + "\\" + data.cFileName;
                if (!harnessDllPath.empty()
                    && _stricmp(dest.c_str(), harnessDllPath.c_str()) == 0) {
                    continue;
                }
                if (CopyFileA(full.c_str(), dest.c_str(), FALSE)) {
                    log += "INFO: 已复制依赖 DLL 到 Harness 目录: ";
                    log += data.cFileName;
                    log += "\n";
                }
            } while (FindNextFileA(find, &data));
            FindClose(find);
        }
    }
}

void UserCodeHarness::ApplyDllSearchPaths() const {
    // Prefer a directory that actually contains .dll (models/), not only .lib.
    for (const auto& dir : m_dllSearchDirs) {
        WIN32_FIND_DATAA data{};
        const std::string pattern = dir + "\\*.dll";
        HANDLE find = FindFirstFileA(pattern.c_str(), &data);
        if (find != INVALID_HANDLE_VALUE) {
            FindClose(find);
            SetDllDirectoryA(dir.c_str());
            return;
        }
    }
    if (!m_dllSearchDirs.empty()) {
        SetDllDirectoryA(m_dllSearchDirs.front().c_str());
    }
}

bool UserCodeHarness::InvokeCl(const UserHarnessConfig& config, const std::string& srcPath,
                               const std::string& outDll, std::string& log) const {
    std::string vcvars = FindVcVars64Bat();
    if (vcvars.empty()) {
        log += "ERROR: 未找到 vcvars64.bat，请确认已安装 Visual Studio C++ 工具集。\n";
        return false;
    }

    std::ostringstream cmd;
    cmd << "cmd.exe /C \"call \"" << vcvars << "\" >nul && ";
    cmd << "cl.exe /nologo /LD /EHa /std:c++14 /O2 /utf-8 /DNOMINMAX ";
    cmd << "/Fe\"" << outDll << "\" ";
    for (const auto& inc : config.includeDirs) {
        cmd << "/I\"" << inc << "\" ";
    }
    for (const auto& h : config.headerPaths) {
        size_t pos = h.find_last_of("/\\");
        if (pos != std::string::npos) {
            cmd << "/I\"" << h.substr(0, pos) << "\" ";
        }
    }
    cmd << "\"" << srcPath << "\" /link ";
    for (const auto& lp : config.libPaths) {
        cmd << "/LIBPATH:\"" << lp << "\" ";
    }
    for (const auto& lib : config.linkLibs) {
        cmd << "\"" << lib << "\" ";
    }
    cmd << "\"";

    SECURITY_ATTRIBUTES sa{};
    sa.nLength = sizeof(sa);
    sa.bInheritHandle = TRUE;
    HANDLE hRead = NULL, hWrite = NULL;
    CreatePipe(&hRead, &hWrite, &sa, 0);
    SetHandleInformation(hRead, HANDLE_FLAG_INHERIT, 0);

    STARTUPINFOW si{};
    si.cb = sizeof(si);
    si.dwFlags = STARTF_USESTDHANDLES;
    si.hStdOutput = hWrite;
    si.hStdError = hWrite;
    PROCESS_INFORMATION pi{};
    std::string mutableCmd = cmd.str();
    log += "CMD: " + mutableCmd + "\n";

    std::wstring wCmd = Utf8ToWide(mutableCmd);
    std::wstring wDir = config.workDir.empty() ? std::wstring() : Utf8ToWide(config.workDir);
    BOOL ok = CreateProcessW(nullptr, wCmd.empty() ? nullptr : &wCmd[0], nullptr, nullptr, TRUE,
                             CREATE_NO_WINDOW, nullptr,
                             wDir.empty() ? nullptr : wDir.c_str(),
                             &si, &pi);
    CloseHandle(hWrite);
    if (!ok) {
        log += "ERROR: CreateProcess 失败，GetLastError=" + std::to_string(GetLastError()) + "\n";
        CloseHandle(hRead);
        return false;
    }

    char buf[1024];
    DWORD rd = 0;
    while (ReadFile(hRead, buf, sizeof(buf) - 1, &rd, nullptr) && rd > 0) {
        buf[rd] = 0;
        log += buf;
    }
    WaitForSingleObject(pi.hProcess, 120000);
    DWORD exitCode = 1;
    GetExitCodeProcess(pi.hProcess, &exitCode);
    CloseHandle(pi.hProcess);
    CloseHandle(pi.hThread);
    CloseHandle(hRead);

    if (exitCode != 0) {
        log += "ERROR: cl.exe 退出码 " + std::to_string(exitCode) + "\n";
        return false;
    }
    std::wstring wOut = Utf8ToWide(outDll);
    if (wOut.empty() || GetFileAttributesW(wOut.c_str()) == INVALID_FILE_ATTRIBUTES) {
        log += "ERROR: 未生成 DLL: " + outDll + "\n";
        return false;
    }
    return true;
}

static bool EnsureDirTreeUtf8(const std::string& utf8Dir) {
    std::wstring w = Utf8ToWide(utf8Dir);
    if (w.empty()) return false;
    // Create intermediate directories
    for (size_t i = 0; i < w.size(); ++i) {
        if (w[i] == L'\\' || w[i] == L'/') {
            if (i == 0) continue;
            // skip "D:" drive root
            if (i == 2 && w[1] == L':') continue;
            wchar_t old = w[i];
            w[i] = L'\0';
            CreateDirectoryW(w.c_str(), nullptr);
            w[i] = old;
        }
    }
    return CreateDirectoryW(w.c_str(), nullptr) != 0 || GetLastError() == ERROR_ALREADY_EXISTS;
}

static bool WriteTextFileUtf8Path(const std::string& utf8Path, const std::string& content, std::string& err) {
    std::wstring w = Utf8ToWide(utf8Path);
    if (w.empty()) {
        err = "路径无效\n";
        return false;
    }
    HANDLE h = CreateFileW(w.c_str(), GENERIC_WRITE, 0, nullptr, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr);
    if (h == INVALID_HANDLE_VALUE) {
        err = "无法写入文件, GetLastError=" + std::to_string(GetLastError()) + "\n";
        return false;
    }
    DWORD written = 0;
    BOOL ok = WriteFile(h, content.data(), static_cast<DWORD>(content.size()), &written, nullptr);
    CloseHandle(h);
    if (!ok) {
        err = "WriteFile 失败, GetLastError=" + std::to_string(GetLastError()) + "\n";
        return false;
    }
    return true;
}

CompileResult UserCodeHarness::Compile(const UserHarnessConfig& config) {
    CompileResult result;
    Unload();

    if (config.userMainBody.find_first_not_of(" \t\r\n") == std::string::npos) {
        result.log = "ERROR: 用户 main 代码为空。\n";
        return result;
    }

    m_enabledVars.clear();
    for (const auto& v : config.randomVars) {
        if (!v.enabled || v.name.empty()) continue;
        // validate identifier
        bool okName = (isalpha(static_cast<unsigned char>(v.name[0])) || v.name[0] == '_');
        for (char c : v.name) {
            if (!isalnum(static_cast<unsigned char>(c)) && c != '_') okName = false;
        }
        if (!okName) {
            result.log += "ERROR: 非法变量名: " + v.name + "\n";
            return result;
        }
        m_enabledVars.push_back(v);
    }

    m_dllSearchDirs.clear();
    std::set<std::string> seen;
    auto addDir = [&](const std::string& d) {
        if (d.empty() || !seen.insert(d).second) return;
        m_dllSearchDirs.push_back(d);
    };
    for (const auto& d : config.libPaths) addDir(d);
    for (const auto& d : config.includeDirs) addDir(d);
    for (const auto& lib : config.linkLibs) {
        size_t pos = lib.find_last_of("/\\");
        if (pos != std::string::npos) addDir(lib.substr(0, pos));
    }

    std::string work = config.workDir;
    if (work.empty()) {
        char tmp[MAX_PATH];
        GetTempPathA(MAX_PATH, tmp);
        work = std::string(tmp) + "ModelPrecheck_Harness";
    }
    if (!EnsureDirTreeUtf8(work)) {
        result.log = "ERROR: 无法创建输出目录: " + work + " (GetLastError=" + std::to_string(GetLastError()) + ")\n";
        // still try if already exists
        std::wstring ww = Utf8ToWide(work);
        DWORD attr = GetFileAttributesW(ww.c_str());
        if (attr == INVALID_FILE_ATTRIBUTES || !(attr & FILE_ATTRIBUTE_DIRECTORY)) {
            return result;
        }
        result.log.clear();
    }

    std::string base = config.outputBaseName.empty() ? "UserHarness" : config.outputBaseName;
    std::string srcPath = work + "\\" + base + ".cpp";
    std::string dllPath = work + "\\" + base + ".dll";
    result.sourcePath = srcPath;

    std::string src = GenerateSource(config, m_enabledVars);
    {
        std::string werr;
        if (!WriteTextFileUtf8Path(srcPath, src, werr)) {
            result.log = "ERROR: " + werr;
            return result;
        }
    }

    {
        std::wstring wDll = Utf8ToWide(dllPath);
        if (!wDll.empty()) DeleteFileW(wDll.c_str());
    }
    UserHarnessConfig cfg = config;
    cfg.workDir = work;
    if (!InvokeCl(cfg, srcPath, dllPath, result.log)) {
        return result;
    }

    CopyDependencyDllsBesideHarness(m_dllSearchDirs, work, dllPath, result.log);

    std::string err;
    if (!LoadCompiledDll(dllPath, err)) {
        result.log += err;
        return result;
    }

    result.success = true;
    result.dllPath = dllPath;
    result.log += "SUCCESS: 编译并加载 " + base + ".dll\n";
    return result;
}

bool UserCodeHarness::LoadCompiledDll(const std::string& dllPath, std::string& err) {
    Unload();
    ApplyDllSearchPaths();

    int n = MultiByteToWideChar(CP_UTF8, 0, dllPath.c_str(), -1, nullptr, 0);
    std::wstring wpath(n > 0 ? n - 1 : 0, L'\0');
    if (n > 1) MultiByteToWideChar(CP_UTF8, 0, dllPath.c_str(), -1, &wpath[0], n);

    m_hModule = LoadLibraryExW(wpath.c_str(), NULL, LOAD_WITH_ALTERED_SEARCH_PATH);
    if (!m_hModule) {
        // Retry with default search after SetDllDirectory
        m_hModule = LoadLibraryW(wpath.c_str());
    }
    if (!m_hModule) {
        err = "LoadLibrary 失败, GetLastError=" + std::to_string(GetLastError())
            + "（请确认 models/ 下的第三方 .dll 存在；工具会尝试复制到 Harness 输出目录）\n";
        return false;
    }
    m_pfnRun = reinterpret_cast<FnRunUserTest>(GetProcAddress(m_hModule, "RunUserTest"));
    if (!m_pfnRun) {
        err = "GetProcAddress(RunUserTest) 失败\n";
        Unload();
        return false;
    }
    m_pfnSetTraj = reinterpret_cast<FnSetTrajectoryCapture>(GetProcAddress(m_hModule, "SetTrajectoryCapture"));
    m_pfnGetTrajCount = reinterpret_cast<FnGetTrajectoryCount>(GetProcAddress(m_hModule, "GetTrajectoryCount"));
    m_pfnGetTrajPoint = reinterpret_cast<FnGetTrajectoryPoint>(GetProcAddress(m_hModule, "GetTrajectoryPoint"));
    m_dllPath = dllPath;
    return true;
}

void UserCodeHarness::Unload() {
    if (m_hModule) {
        FreeLibrary(m_hModule);
        m_hModule = NULL;
    }
    m_pfnRun = nullptr;
    m_pfnSetTraj = nullptr;
    m_pfnGetTrajCount = nullptr;
    m_pfnGetTrajPoint = nullptr;
    m_dllPath.clear();
    SetDllDirectoryA(nullptr);
}

RandomValueBlob UserCodeHarness::Sample(uint32_t seed) const {
    RandomValueBlob blob;
    std::mt19937 rng(seed);
    std::ostringstream sum;
    for (const auto& v : m_enabledVars) {
        if (v.type == RandomVarType::Int) {
            int lo = static_cast<int>(std::floor(v.minValue));
            int hi = static_cast<int>(std::floor(v.maxValue));
            if (hi < lo) std::swap(hi, lo);
            std::uniform_int_distribution<int> dist(lo, hi);
            int x = dist(rng);
            blob.ints.push_back(x);
            sum << v.name << "=" << x << " ";
        } else {
            double lo = v.minValue, hi = v.maxValue;
            if (hi < lo) std::swap(hi, lo);
            std::uniform_real_distribution<double> dist(lo, hi);
            double x = dist(rng);
            blob.doubles.push_back(x);
            sum << v.name << "=" << x << " ";
        }
    }
    blob.summary = sum.str();
    return blob;
}

typedef int (*FnRunUserTestRaw)(const double*, int, const int*, int);

static int InvokeRunUserTestRaw(FnRunUserTestRaw fn, const double* d, int nd, const int* iv, int ni, DWORD* outExc) {
    if (!fn) {
        if (outExc) *outExc = static_cast<DWORD>(-1);
        return 0;
    }
    __try {
        if (outExc) *outExc = 0;
        return fn(d, nd, iv, ni);
    }
    __except (EXCEPTION_EXECUTE_HANDLER) {
        if (outExc) *outExc = GetExceptionCode();
        return 0;
    }
}

bool UserCodeHarness::RunOnce(const RandomValueBlob& values, int* outUserReturn, bool* outSeh, std::string& err) const {
    if (!m_pfnRun) {
        err = "Harness DLL 未加载";
        return false;
    }
    DWORD exc = 0;
    int ret = InvokeRunUserTestRaw(
        reinterpret_cast<FnRunUserTestRaw>(m_pfnRun),
        values.doubles.empty() ? nullptr : values.doubles.data(),
        static_cast<int>(values.doubles.size()),
        values.ints.empty() ? nullptr : values.ints.data(),
        static_cast<int>(values.ints.size()),
        &exc);

    if (exc != 0) {
        if (outSeh) *outSeh = true;
        std::ostringstream oss;
        oss << "SEH 异常 0x" << std::hex << exc;
        err = oss.str();
        return false;
    }
    if (outSeh) *outSeh = false;
    if (outUserReturn) *outUserReturn = ret;
    return true;
}

bool UserCodeHarness::SetTrajectoryCapture(bool enabled) const {
    if (!m_pfnSetTraj) return false;
    m_pfnSetTraj(enabled ? 1 : 0);
    return true;
}

bool UserCodeHarness::FetchTrajectory(std::vector<TrajectorySample>& out) const {
    out.clear();
    if (!m_pfnGetTrajCount || !m_pfnGetTrajPoint) return false;
    const int n = m_pfnGetTrajCount();
    if (n <= 0) return true;
    out.reserve(static_cast<size_t>(n));
    for (int i = 0; i < n; ++i) {
        TrajectorySample s;
        if (!m_pfnGetTrajPoint(i, &s.lat, &s.lon)) continue;
        out.push_back(s);
    }
    return true;
}
